# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

# dbpostgres:
#     type: postgresql:12
#     disk: 256

dbmongo:
    type: mongodb:3.6
    disk: 512

# dbmysql:
#     type: oracle-mysql:8.0
#     disk: 256
